CREATE TABLE mtorg_db.trka_groups_groups
(
    id int(10) unsigned PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    parent int(11) DEFAULT 0 NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    deleted_at timestamp,
    forum_channel_id int(11),
    homepage_content longtext,
    homepage_content_html longtext,
    group_type varchar(255) NOT NULL,
    group_icon varchar(255) NOT NULL,
    group_color varchar(255) NOT NULL,
    transifex_url varchar(255),
    notices text,
    sidebar_slots text
);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (1, 'Mauticamp Boston', 'mauticamp-boston', 'Welcome to your Boston-based marketing automation networking group focused on Mautic! Come see what we are all about at our next monthly meeting.', 0, '2018-06-23 00:58:53', '2018-06-26 19:55:59', null, 102406, '<h2>Welcome to your Mauticamp Boston</h2>
If you''re looking for the best Mauticamp in all of the Eastern United States then you are in the right place! Mauticamp Boston meets once a month at the HQ for Mautic, Inc. We chat about all things MarTech!', '<h2>Welcome to your Mauticamp Boston</h2>
<p>If you''re looking for the best Mauticamp in all of the Eastern United States then you are in the right place! Mauticamp Boston meets once a month at the HQ for Mautic, Inc. We chat about all things MarTech!</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (2, 'Documentation Working Group', 'documentation-working-group', 'Hardly anyone likes to write documentation but everyone likes to read it. Our working group is therefore one of the most important in all of Mautic. If you have the ability to read code and explain it to others, come join us and be a Mautic hero.', 0, '2018-06-23 02:09:34', '2018-06-30 13:20:07', null, 104421, 'Hardly anyone likes to write documentation but everyone likes to read it. Our working group is therefore one of the most important in all of Mautic. If you have the ability to read code and explain it to others, come join us and be a Mautic hero.', '<p>Hardly anyone likes to write documentation but everyone likes to read it. Our working group is therefore one of the most important in all of Mautic. If you have the ability to read code and explain it to others, come join us and be a Mautic hero.</p>', 'working-group', 'fe-edit-3', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (3, 'Security Working Group', 'security-working-group', 'We''re like the super-stealth strike team for Mautic code. Our mission is to fix those critical security bugs before anyone else finds them. We require immediate response times from our team members and a high level of trust. Are you up for the challenge?', 0, '2018-06-23 03:57:21', '2018-07-07 21:06:57', null, 68638, '', '', 'working-group', 'fe-shield', 'gray', '', '[{"title":"Foo","color_class":"primary","button_text":"Something happened","link_target":""},{"title":"Bar","color_class":"secondary","button_text":"A Thing","link_target":""}]', '[{"title":"Next Meeting","subtext":"11\\/08\\/2018","container_styles":"bg-brand-purple","icon_class":"fe-calendar","link_target":""}]');
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (4, 'Issues Working Group', 'issues-working-group', 'Thankfully our group doesn''t have to solve all the issues in Mautic. But we do triage them, help to organize them and coordinate with the Mautic development community to make sure everyone works most effectively. We''d love your help!', 0, '2018-06-23 03:58:00', '2018-06-30 13:20:19', null, 104423, 'Thankfully our group doesn''t have to solve all the issues in Mautic. But we do triage them, help to organize them and coordinate with the Mautic development community to make sure everyone works most effectively. We''d love your help!', '<p>Thankfully our group doesn''t have to solve all the issues in Mautic. But we do triage them, help to organize them and coordinate with the Mautic development community to make sure everyone works most effectively. We''d love your help!</p>', 'working-group', 'fe-alert-circle', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (5, 'Translations Working Group', 'translations-working-group', '¿hablas español? or あなたは日本語を話せますか？or another language? Our translations working group is focused on improving the Mautic software language translations, and we need your help. We have open requests needing your specific skills.', 0, '2018-06-23 03:59:19', '2018-06-30 13:16:16', null, 104434, '', '', 'working-group', 'fe-headphones', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (6, 'Mauticamp South Africa', 'mauticamp-south-africa', 'Corporate Strength Marketing for All.
Now Small businesses can also market like the big guys…With Mautic leveling the playing fields.', 0, '2018-06-24 19:10:24', '2018-06-26 19:55:19', null, 102673, '', '', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (7, 'Mauticamp Germany', 'mauticamp-germany', 'Mautic ist als Marketing Automation Software nicht nur technisch stark und voll im Trend, sondern hat gleichzeitig auch die Verteile eines Open Source Projekts.', 0, '2018-06-26 19:18:37', '2018-06-26 19:53:01', null, 68636, '<h2>Willkommen in Mauticamp Deutschland!</h2>
Mautic ist als Marketing Automation Software nicht nur technisch stark und voll im Trend, sondern hat gleichzeitig auch die Verteile eines Open Source Projekts.

Höchste Zeit, auch in Deutschland die wachsende Community näher zusammenzubringen!', '<h2>Willkommen in Mauticamp Deutschland!</h2>
<p>Mautic ist als Marketing Automation Software nicht nur technisch stark und voll im Trend, sondern hat gleichzeitig auch die Verteile eines Open Source Projekts.</p>
<p>Höchste Zeit, auch in Deutschland die wachsende Community näher zusammenzubringen!</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (8, 'Mauticamp München', 'mauticamp-munchen', 'Mautic ist eine Open-Source-Marketing-Automatisierungssoftware, die auf der neuesten PHP-Architektur aufbaut.', 0, '2018-06-26 19:58:29', '2018-06-26 20:02:04', null, 68636, '<h2>Willkommen in Mauticamp München!</h2>
Mautic ist eine Open-Source-Marketing-Automatisierungssoftware, die auf der neuesten PHP-Architektur aufbaut.

Treffen Sie sich, um Wissen mit allen in München zu teilen, die sich für diese wundervolle Marketing-Plattform interessieren, einschließlich Best Practices zur Verwendung von Mautic und wie man es anpasst.', '<h2>Willkommen in Mauticamp München!</h2>
<p>Mautic ist eine Open-Source-Marketing-Automatisierungssoftware, die auf der neuesten PHP-Architektur aufbaut.</p>
<p>Treffen Sie sich, um Wissen mit allen in München zu teilen, die sich für diese wundervolle Marketing-Plattform interessieren, einschließlich Best Practices zur Verwendung von Mautic und wie man es anpasst.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (9, 'Mauticamp Nagoya', 'mauticamp-nagoya', 'ある名古屋市の皆さんの知識を共有するためのミートアップ。', 0, '2018-06-26 20:00:43', '2018-06-26 20:03:33', null, 68636, '<h2>ある名古屋市の皆さんの知識を共有するためのミートアップ。</h2>
Mauticは、最新のPHPアーキテクチャー上に構築されたオープンソースのマーケティングオートメーションソフトウェアです。 Mauticの使い方やカスタマイズ方法のベストプラクティスなど、この素晴らしいマーケティングプラットフォームに関心のある名古屋市の皆さんの知識を共有するためのミートアップ。', '<h2>ある名古屋市の皆さんの知識を共有するためのミートアップ。</h2>
<p>Mauticは、最新のPHPアーキテクチャー上に構築されたオープンソースのマーケティングオートメーションソフトウェアです。 Mauticの使い方やカスタマイズ方法のベストプラクティスなど、この素晴らしいマーケティングプラットフォームに関心のある名古屋市の皆さんの知識を共有するためのミートアップ。</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (10, 'Mauticamp India', 'mauticamp-india', 'Meet up to share knowledge with everyone in INDIA who is interested in this wonderful marketing platform.', 0, '2018-06-26 20:04:28', '2018-06-26 20:04:28', null, 68636, '<h2>Welcome to Mauticamp India</h2>
Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in INDIA who is interested in this wonderful marketing platform.

Use this platform and boost your business.', '<h2>Welcome to Mauticamp India</h2>
<p>Mautic is an open source marketing automation software built on the latest PHP architecture.</p>
<p>Meet up to share knowledge with everyone in INDIA who is interested in this wonderful marketing platform.</p>
<p>Use this platform and boost your business.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (11, 'Mauticamp New York', 'mauticamp-new-york', 'Meet up to share knowledge with everyone in New York who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.', 0, '2018-06-27 14:53:38', '2018-06-27 14:53:38', null, 68636, '<h2> Hello! New York Mauticamp</h2>
Meet up to share knowledge with everyone in New York who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.', '<h2> Hello! New York Mauticamp</h2>
<p>Meet up to share knowledge with everyone in New York who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (12, 'Mauticamp Switzerland', 'mauticamp-switzerland', 'Meet up to share knowledge with everyone in Switzerland who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.', 0, '2018-06-27 14:54:15', '2018-06-27 14:54:15', null, 68636, '<h2>Welcome to Mauticamp Switzerland</h2>
Meet up to share knowledge with everyone in Switzerland who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.', '<h2>Welcome to Mauticamp Switzerland</h2>
<p>Meet up to share knowledge with everyone in Switzerland who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (13, 'Mauticamp España', 'mauticamp-espana', 'Para los que nos peleamos por España, y en castellano…', 0, '2018-06-27 14:55:00', '2018-06-27 14:55:00', null, 68636, '<h2>Mauticamp España</h2>
Para los que nos peleamos por España, y en castellano…', '<h2>Mauticamp España</h2>
<p>Para los que nos peleamos por España, y en castellano…</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (14, 'Mauticamp Virginia', 'mauticamp-virginia', 'Link up to share knowledge with the communities in Virginia and surrounding areas who are interested in this game changing marketing platform. Topics including how to install & use Mautic, as well as, best practices and how to customize it.', 0, '2018-06-27 14:55:49', '2018-06-27 14:55:49', null, 68636, '<h2>Welcome to Mauticamp Virginia</h2>

<h3>Corporate Strength Marketing for All.</h3>

Now Small businesses can also market like the big guys…Mautic levels the playing field, empowering SMB owners with powerful marketing automation software built on the latest PHP architecture.

Link up to share knowledge with the communities in Virginia and surrounding areas who are interested in this game changing marketing platform. Topics including how to install & use Mautic, as well as, best practices and how to customize it.', '<h2>Welcome to Mauticamp Virginia</h2>
<h3>Corporate Strength Marketing for All.</h3>
<p>Now Small businesses can also market like the big guys…Mautic levels the playing field, empowering SMB owners with powerful marketing automation software built on the latest PHP architecture.</p>
<p>Link up to share knowledge with the communities in Virginia and surrounding areas who are interested in this game changing marketing platform. Topics including how to install &amp; use Mautic, as well as, best practices and how to customize it.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (15, 'Mauticamp Indonesia', 'mauticamp-indonesia', 'We will hold free training and routine workshop at least 3 months', 0, '2018-06-27 14:59:33', '2018-06-27 14:59:33', null, 68636, '<h2> Welcome to Mauticamp Indonesia</h2>
We will hold free training and routine workshop at least 3 months.', '<h2> Welcome to Mauticamp Indonesia</h2>
<p>We will hold free training and routine workshop at least 3 months.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (16, 'Mauticamp Prague', 'mauticamp-prague', 'Setkávejte se s partnery, kteří se zajímají o tuto skvělou marketingovou platformu, včetně osvědčených postupů, jak používat Mautic a jak je přizpůsobit.', 0, '2018-06-27 15:00:12', '2018-06-27 15:00:12', null, 68636, '<h2>Welcome to Mauticamp Prague!</h2>
Mautic je software pro automatizaci marketingu s otevřeným zdrojovým kódem postavený na nejnovější architektuře PHP.

Setkávejte se s partnery, kteří se zajímají o tuto skvělou marketingovou platformu, včetně osvědčených postupů, jak používat Mautic a jak je přizpůsobit.', '<h2>Welcome to Mauticamp Prague!</h2>
<p>Mautic je software pro automatizaci marketingu s otevřeným zdrojovým kódem postavený na nejnovější architektuře PHP.</p>
<p>Setkávejte se s partnery, kteří se zajímají o tuto skvělou marketingovou platformu, včetně osvědčených postupů, jak používat Mautic a jak je přizpůsobit.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (17, 'Mauticamp Latino América', 'mauticamp-latino-america', 'Bienvenido(a) a la Comunidad de MautiCamp Latinoamérica para: Perú, Colombia, Ecuador, Chile, Argentina, México, entre otros.', 0, '2018-06-27 15:01:07', '2018-06-27 15:01:07', null, 68636, '<h2>Bienvenido(a) a la Comunidad de MautiCamp Latinoamérica!</h2>
Para: Perú, Colombia, Ecuador, Chile, Argentina, México, entre otros.

Mautic es el primer software open source de automatización del marketing más completo. Posee características avanzadas para generar demanda, nutrir y calificar leads, aumentar el engagement y facilitar la fidelización.

Esta es la primera comunidad en español para Latinoamérica. Un reto que asumimos juntos para difundir el conocimiento y uso de Mautic a estudiantes, profesionales del marketing y a desarrolladores.', '<h2>Bienvenido(a) a la Comunidad de MautiCamp Latinoamérica!</h2>
<p>Para: Perú, Colombia, Ecuador, Chile, Argentina, México, entre otros.</p>
<p>Mautic es el primer software open source de automatización del marketing más completo. Posee características avanzadas para generar demanda, nutrir y calificar leads, aumentar el engagement y facilitar la fidelización.</p>
<p>Esta es la primera comunidad en español para Latinoamérica. Un reto que asumimos juntos para difundir el conocimiento y uso de Mautic a estudiantes, profesionales del marketing y a desarrolladores.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (18, 'Mauticamp Sweden', 'mauticamp-sweden', 'The home for Mautic in Sweden', 0, '2018-06-27 20:00:55', '2018-06-27 20:01:05', null, 102406, '<h2>Welcome to Mauticamp Sweden!</h2>', '<h2>Welcome to Mauticamp Sweden!</h2>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (19, 'Mauticamp London', 'mauticamp-london', 'Meet up to share knowledge of everyone in London who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.', 0, '2018-06-27 20:01:49', '2018-06-27 20:01:49', null, 68636, '<h2>Welcome to Mauticamp London</h2>
Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge of everyone in London who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.', '<h2>Welcome to Mauticamp London</h2>
<p>Mautic is an open source marketing automation software built on the latest PHP architecture.</p>
<p>Meet up to share knowledge of everyone in London who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (20, 'Mauticamp Malága', 'mauticamp-malaga', 'Reúnete para compartir conocimientos con todos los que están interesados en esta maravillosa plataforma de marketing, incluidas las mejores prácticas sobre cómo usar Mautic y cómo personalizarlas.', 0, '2018-06-27 20:04:09', '2018-06-27 20:04:09', null, 68636, '<h2>Welcome to Mauticamp Malága</h2>
Mautic es un software de automatización de marketing de código abierto basado en la última arquitectura de PHP.

Reúnete para compartir conocimientos con todos los que están interesados en esta maravillosa plataforma de marketing, incluidas las mejores prácticas sobre cómo usar Mautic y cómo personalizarlas.', '<h2>Welcome to Mauticamp Malága</h2>
<p>Mautic es un software de automatización de marketing de código abierto basado en la última arquitectura de PHP.</p>
<p>Reúnete para compartir conocimientos con todos los que están interesados en esta maravillosa plataforma de marketing, incluidas las mejores prácticas sobre cómo usar Mautic y cómo personalizarlas.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (21, 'Mauticamp Chicago', 'mauticamp-chicago', 'Meet up to share knowledge with everyone in Chicago who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.', 0, '2018-06-27 20:05:08', '2018-06-27 20:05:08', null, 68636, '<h2>Welcome to Mauticamp Chicago</h2>
Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in Chicago who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.', '<h2>Welcome to Mauticamp Chicago</h2>
<p>Mautic is an open source marketing automation software built on the latest PHP architecture.</p>
<p>Meet up to share knowledge with everyone in Chicago who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (22, 'Mauticamp Vietname', 'mauticamp-vietname', 'Đây là nơi dành cho người Việt Nam – những người quan tâm đến nền tảng tiếp thị tuyệt vời chia sẻ kiến thức.', 0, '2018-06-27 20:05:40', '2018-06-27 20:05:40', null, 68636, '<h2>Welcome to Mauticamp Vietnam</h2>
Mautic là một phần mềm tự động hóa tiếp thị mã nguồn mở được xây dựng trên kiến ​​trúc PHP mới nhất.

Đây là nơi dành cho người Việt Nam – những người quan tâm đến nền tảng tiếp thị tuyệt vời chia sẻ kiến thức.', '<h2>Welcome to Mauticamp Vietnam</h2>
<p>Mautic là một phần mềm tự động hóa tiếp thị mã nguồn mở được xây dựng trên kiến ​​trúc PHP mới nhất.</p>
<p>Đây là nơi dành cho người Việt Nam – những người quan tâm đến nền tảng tiếp thị tuyệt vời chia sẻ kiến thức.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (23, 'Mauticamp Paris', 'mauticamp-paris', 'Rendez-vous pour partager des connaissances avec tout le monde à Paris qui est intéressé par cette merveilleuse plate-forme de marketing, y compris les meilleures pratiques sur la façon d’utiliser Mautic et comment le personnaliser.', 0, '2018-06-27 20:06:42', '2018-06-27 20:06:42', null, 68636, '<h2>Welcome to Mauticamp Paris</h2>
Mautic est un logiciel d’automatisation de marketing open source basé sur la dernière architecture PHP.

Rendez-vous pour partager des connaissances avec tout le monde à Paris qui est intéressé par cette merveilleuse plate-forme de marketing, y compris les meilleures pratiques sur la façon d’utiliser Mautic et comment le personnaliser.', '<h2>Welcome to Mauticamp Paris</h2>
<p>Mautic est un logiciel d’automatisation de marketing open source basé sur la dernière architecture PHP.</p>
<p>Rendez-vous pour partager des connaissances avec tout le monde à Paris qui est intéressé par cette merveilleuse plate-forme de marketing, y compris les meilleures pratiques sur la façon d’utiliser Mautic et comment le personnaliser.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (24, 'Mauticamp Kobe', 'mauticamp-kobe', 'Mauticの使い方とカスタマイズ方法に関するベストプラクティスなど、この素晴らしいマーケティングプラットフォームに関心を持つ神戸の皆さんと知識を共有しましょう。', 0, '2018-06-27 20:08:45', '2018-06-27 20:08:45', null, 68636, '<h2>持つ神戸の皆さんと知識を共有しましょう。</h2>
Mauticは、最新のPHPアーキテクチャー上に構築されたオープンソースのマーケティングオートメーションソフトウェアです。

Mauticの使い方とカスタマイズ方法に関するベストプラクティスなど、この素晴らしいマーケティングプラットフォームに関心を持つ神戸の皆さんと知識を共有しましょう。', '<h2>持つ神戸の皆さんと知識を共有しましょう。</h2>
<p>Mauticは、最新のPHPアーキテクチャー上に構築されたオープンソースのマーケティングオートメーションソフトウェアです。</p>
<p>Mauticの使い方とカスタマイズ方法に関するベストプラクティスなど、この素晴らしいマーケティングプラットフォームに関心を持つ神戸の皆さんと知識を共有しましょう。</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (25, 'Mauticamp Osaka', 'mauticamp-osaka', 'Mauticの使い方とカスタマイズ方法に関するベストプラクティスなど、このすばらしいマーケティングプラットフォームに関心を持つ大阪の皆さんの知識を共有しましょう。', 0, '2018-06-27 20:09:47', '2018-06-27 20:09:47', null, 68636, '<h2>つ大阪の皆さんの知識を共有しましょう。</h2>
Mauticは、最新のPHPアーキテクチャー上に構築されたオープンソースのマーケティングオートメーションソフトウェアです。

Mauticの使い方とカスタマイズ方法に関するベストプラクティスなど、このすばらしいマーケティングプラットフォームに関心を持つ大阪の皆さんの知識を共有しましょう。', '<h2>つ大阪の皆さんの知識を共有しましょう。</h2>
<p>Mauticは、最新のPHPアーキテクチャー上に構築されたオープンソースのマーケティングオートメーションソフトウェアです。</p>
<p>Mauticの使い方とカスタマイズ方法に関するベストプラクティスなど、このすばらしいマーケティングプラットフォームに関心を持つ大阪の皆さんの知識を共有しましょう。</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (26, 'Mauticamp Vancouver', 'mauticamp-vancouver', 'Join this group if you are in Vancouver Canada. Let’s share our Mautic knowledge to create butt-kicking marketing campaigns.  ?', 0, '2018-06-27 20:11:38', '2018-06-27 20:11:38', null, 68636, '<h2>Welcome to Mauticamp Vancouver</h2>
Join this group if you are in Vancouver Canada. Let’s share our Mautic knowledge to create butt-kicking marketing campaigns. ?', '<h2>Welcome to Mauticamp Vancouver</h2>
<p>Join this group if you are in Vancouver Canada. Let’s share our Mautic knowledge to create butt-kicking marketing campaigns. ?</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (27, 'Mauticamp Poland', 'mauticamp-poland', 'Społeczność Mautic w Polsce', 0, '2018-06-27 20:12:15', '2018-06-27 20:12:15', null, 68636, '<h2>Welcome to Mauticamp Poland</h2>
Społeczność Mautic w Polsce', '<h2>Welcome to Mauticamp Poland</h2>
<p>Społeczność Mautic w Polsce</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (28, 'Mauticamp Italia', 'mauticamp-italia', 'Aiutaci a sviluppare una comunità italiana per la promozione dell’Open Marketing, l’Open Innovation e di Mautic.', 0, '2018-06-27 20:13:04', '2018-06-27 20:13:04', null, 68636, '<h2>Welcome to Mauticamp Italia</h2>
Mautic is an open source marketing automation software built on the latest PHP architecture.
Meet up to share knowledge with everyone in Italy who is interested in this wonderful marketing platform.
Use this platform and boost your business, your brand or your values.
Aiutaci a sviluppare una comunità italiana per la promozione dell’Open Marketing, l’Open Innovation e di Mautic.', '<h2>Welcome to Mauticamp Italia</h2>
<p>Mautic is an open source marketing automation software built on the latest PHP architecture.
Meet up to share knowledge with everyone in Italy who is interested in this wonderful marketing platform.
Use this platform and boost your business, your brand or your values.
Aiutaci a sviluppare una comunità italiana per la promozione dell’Open Marketing, l’Open Innovation e di Mautic.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (29, 'Mauticamp Rio De Janeiro', 'mauticamp-rio-de-janeiro', 'Encontro de usuários do Mautic no Rio de Janeiro', 0, '2018-06-27 20:20:57', '2018-06-27 20:20:57', null, 68636, '<h2>Welcome to Mauticamp Rio De Janeiro</h2>
Encontro de usuários do Mautic no Rio de Janeiro', '<h2>Welcome to Mauticamp Rio De Janeiro</h2>
<p>Encontro de usuários do Mautic no Rio de Janeiro</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (30, 'Mauticamp Montréal', 'mauticamp-montreal', 'Rendez-vous pour partager les connaissances de tout le monde à Montréal, QC qui s’intéresse à cette merveilleuse plate-forme de marketing, y compris les meilleures pratiques sur l’utilisation de Mautic et la façon de le personnaliser.', 0, '2018-06-27 20:25:08', '2018-06-27 20:25:08', null, 68636, '<h2>Welcome to Mauticamp Montréal</h2>
Mautic est un logiciel d’automatisation de marketing open source basé sur la dernière architecture PHP.

Rendez-vous pour partager les connaissances de tout le monde à Montréal, QC qui s’intéresse à cette merveilleuse plate-forme de marketing, y compris les meilleures pratiques sur l’utilisation de Mautic et la façon de le personnaliser.', '<h2>Welcome to Mauticamp Montréal</h2>
<p>Mautic est un logiciel d’automatisation de marketing open source basé sur la dernière architecture PHP.</p>
<p>Rendez-vous pour partager les connaissances de tout le monde à Montréal, QC qui s’intéresse à cette merveilleuse plate-forme de marketing, y compris les meilleures pratiques sur l’utilisation de Mautic et la façon de le personnaliser.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (31, 'Mauticamp Hong Kong', 'mauticamp-hong-kong', 'Meet up to share knowledge with everyone in Hong Kong who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.', 0, '2018-06-27 20:40:36', '2018-06-27 20:40:36', null, 68636, '<h2>Welcome to Mauticamp Hong Kong</h2>
Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in Hong Kong who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.', '<h2>Welcome to Mauticamp Hong Kong</h2>
<p>Mautic is an open source marketing automation software built on the latest PHP architecture.</p>
<p>Meet up to share knowledge with everyone in Hong Kong who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (32, 'Mauticamp Malaysia', 'mauticamp-malaysia', 'Meet up to share knowledge with everyone in Malaysia who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.', 0, '2018-06-27 20:41:54', '2018-06-27 20:41:54', null, 68636, '<h2>Welcome to Mauticamp Malaysia</h2>
Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in Malaysia who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.', '<h2>Welcome to Mauticamp Malaysia</h2>
<p>Mautic is an open source marketing automation software built on the latest PHP architecture.</p>
<p>Meet up to share knowledge with everyone in Malaysia who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (33, 'Mauticamp Singapore', 'mauticamp-singapore', 'Meet up to share knowledge with everyone in Singapore who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.', 0, '2018-06-27 20:51:38', '2018-06-27 20:51:38', null, 68636, '<h2>Welcome to Mauticamp Singapore!</h2>
Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in Singapore who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.', '<h2>Welcome to Mauticamp Singapore!</h2>
<p>Mautic is an open source marketing automation software built on the latest PHP architecture.</p>
<p>Meet up to share knowledge with everyone in Singapore who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how to customize it.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (34, 'Mauticamp Hungary', 'mauticamp-hungary', 'Ha Mautic használó magyarokkal akarsz kapcsolatba kerülni, akkor csatlakozz itt.', 0, '2018-06-27 20:52:34', '2018-06-27 20:52:34', null, 68636, '<h2>Welcome to Mauticamp Hungary</h2>
Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in Hungary who is interested in this wonderful marketing platform, including […]

Ha Mautic használó magyarokkal akarsz kapcsolatba kerülni, akkor csatlakozz itt.', '<h2>Welcome to Mauticamp Hungary</h2>
<p>Mautic is an open source marketing automation software built on the latest PHP architecture.</p>
<p>Meet up to share knowledge with everyone in Hungary who is interested in this wonderful marketing platform, including […]</p>
<p>Ha Mautic használó magyarokkal akarsz kapcsolatba kerülni, akkor csatlakozz itt.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (35, 'Mauticamp Belgium', 'mauticamp-belgium', 'Ontmoet om kennis te delen met iedereen in België die geïnteresseerd is in dit prachtige marketingplatform, inclusief de beste werkwijzen over hoe je Mautic kunt gebruiken en hoe je het kunt aanpassen.', 0, '2018-06-27 20:54:11', '2018-06-27 20:54:11', null, 68636, '<h2>Welcome to Mauticamp Belgium</h2>
Mautic is een open source marketing automation software gebouwd op de nieuwste PHP-architectuur.

Ontmoet om kennis te delen met iedereen in België die geïnteresseerd is in dit prachtige marketingplatform, inclusief de beste werkwijzen over hoe je Mautic kunt gebruiken en hoe je het kunt aanpassen.', '<h2>Welcome to Mauticamp Belgium</h2>
<p>Mautic is een open source marketing automation software gebouwd op de nieuwste PHP-architectuur.</p>
<p>Ontmoet om kennis te delen met iedereen in België die geïnteresseerd is in dit prachtige marketingplatform, inclusief de beste werkwijzen over hoe je Mautic kunt gebruiken en hoe je het kunt aanpassen.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (36, 'Mauticamp São Paulo', 'mauticamp-sao-paulo', 'Meetup para compartilhar conhecimento de todos no Japão interessados nesta maravilhosa plataforma de marketing, como as melhores práticas de como usar e personalizar Mautic.', 0, '2018-06-27 20:56:18', '2018-06-27 20:56:18', null, 68636, '<h2>Welcome to Mauticamp São Paulo</h2>
Mautic é um software de automação de marketing de código aberto, construído com uma moderna arquitetura PHP. Meetup para compartilhar conhecimento de todos no Japão interessados nesta maravilhosa plataforma de marketing, como as melhores práticas de como usar e personalizar Mautic.', '<h2>Welcome to Mauticamp São Paulo</h2>
<p>Mautic é um software de automação de marketing de código aberto, construído com uma moderna arquitetura PHP. Meetup para compartilhar conhecimento de todos no Japão interessados nesta maravilhosa plataforma de marketing, como as melhores práticas de como usar e personalizar Mautic.</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (37, 'Mauticamp Israel', 'mauticamp-israel', 'מאוטיק היא תוכנת מארקטינג אוטומיישן מבוססת קוד פתוח שנבנתה על תשתית פי.אייץ’.פי. כאן ניתן להפגש ולחלוק מידע עם כל מי שמתעניין במערכת זו, כולל מידע על שיטות עבודה מומלצות וכיצד ניתן לבצע במערכת התאמות אישיות', 0, '2018-06-27 20:57:42', '2018-06-27 20:57:42', null, 68636, '<h2>Welcome to Mauticamp ישראל</h2>
מאוטיק היא תוכנת מארקטינג אוטומיישן מבוססת קוד פתוח שנבנתה על תשתית פי.אייץ’.פי. כאן ניתן להפגש ולחלוק מידע עם כל מי שמתעניין במערכת זו, כולל מידע על שיטות עבודה מומלצות וכיצד ניתן לבצע במערכת התאמות אישיו', '<h2>Welcome to Mauticamp ישראל</h2>
<p>מאוטיק היא תוכנת מארקטינג אוטומיישן מבוססת קוד פתוח שנבנתה על תשתית פי.אייץ’.פי. כאן ניתן להפגש ולחלוק מידע עם כל מי שמתעניין במערכת זו, כולל מידע על שיטות עבודה מומלצות וכיצד ניתן לבצע במערכת התאמות אישיו</p>', 'mauticamp', '', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (38, 'Security Working Group', 'security-working-group', '', 0, '2018-06-28 12:37:10', '2018-06-28 12:58:25', '2018-06-28 12:58:25', 68637, '', '', 'working-group', 'fe-shield', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (39, 'Releases Working Group', 'releases-working-group', 'There''s a certain thrill which comes from pushing the big red release button on the Mautic software releases. Our team is a closely moderated team of dev experts focused on ensuring on-time, seamless software updates.', 0, '2018-06-28 12:37:43', '2018-06-30 13:15:49', null, 104429, '', '', 'working-group', 'fe-package', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (40, 'API Working Group', 'api-working-group', 'We are a product-focused working group creating and improving the API layer of the Mautic marketing automation platform. Our focus is all code and making it connectable to everything via endpoints. We are always looking for other technical experts!', 0, '2018-06-28 12:38:47', '2018-06-30 13:14:22', null, 104419, 'We are a product-focused working group creating and improving the API layer of the Mautic marketing automation platform. Our focus is all code and making it connectable to everything via endpoints. We are always looking for other technical experts!', '<p>We are a product-focused working group creating and improving the API layer of the Mautic marketing automation platform. Our focus is all code and making it connectable to everything via endpoints. We are always looking for other technical experts!</p>', 'working-group', 'fe-git-commit', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (41, 'Frontend Working Group', 'frontend-working-group', 'This is a product-focused working group with special attention paid to the frontend and user interface of the Mautic marketing automation platform. If you''ve got an eye for UX or just like making sure things look just right, consider joining our group.', 0, '2018-06-28 12:39:12', '2018-06-30 13:20:13', null, 104422, 'This is a product-focused working group with special attention paid to the frontend and user interface of the Mautic marketing automation platform. If you''ve got an eye for UX or just like making sure things look just right, consider joining our group.', '<p>This is a product-focused working group with special attention paid to the frontend and user interface of the Mautic marketing automation platform. If you''ve got an eye for UX or just like making sure things look just right, consider joining our group.</p>', 'working-group', 'fe-monitor', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (42, 'Blog Working Group', 'blog-working-group', 'Our working group is focused on writing. As a matter of fact, we post fresh content to the Mautic blog all the time, and we''re always hoping to expand our topics and expertise. Oh, and bi-lingual or translators are very, very welcome!', 0, '2018-06-28 12:39:26', '2018-06-30 13:19:52', null, 104420, 'Our working group is focused on writing. As a matter of fact, we post fresh content to the Mautic blog all the time, and we''re always hoping to expand our topics and expertise. Oh, and bi-lingual or translators are very, very welcome!', '<p>Our working group is focused on writing. As a matter of fact, we post fresh content to the Mautic blog all the time, and we''re always hoping to expand our topics and expertise. Oh, and bi-lingual or translators are very, very welcome!</p>', 'working-group', 'fe-rss', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (43, 'Newsletter Working Group', 'newsletter-working-group', 'We gather Mautic headlines from around the web throughout the month and then put all that incredible information into one jam-packed monthly newsletter. If you like scouring the web and sharing what you find, or you enjoy writing you belong here.', 0, '2018-06-28 12:39:44', '2018-06-30 13:15:42', null, 104428, '', '', 'working-group', 'fe-file', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (44, 'Marketplace Working Group', 'marketplace-working-group', 'We love sharing in the Mautic Marketplace. Our working group is focused on reviewing & approving new mixins before they are shared in the Marketplace. In the early days it''s not super time-intensive, but the responsibilities are empowering, want to help?', 0, '2018-06-28 12:41:17', '2018-06-30 13:14:55', null, 104424, '', '', 'working-group', 'fe-briefcase', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (45, 'Webmaster Working Group', 'webmaster-working-group', 'This amazing website doesn''t run itself. We''re the working group behind the amazing Mautic.org and all the other websites associated with our community. If you like tinkering with HTML or want to help make our web presence better, this is your home.', 0, '2018-06-28 12:41:43', '2018-06-30 13:16:21', null, 104435, '', '', 'working-group', 'fe-globe', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (46, 'Mauticians Working Group', 'mauticians-working-group', 'Keeping track of who''s doing what and all the many tens of thousands of Mauticians is a daunting task. We like challenges though. Our Mauticians working group focuses on helping Mauticians get connected and share their expertise.', 0, '2018-06-28 12:42:06', '2018-06-30 13:15:26', null, 104426, '', '', 'working-group', 'fe-user-check', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (47, 'Mauticon Working Group', 'mauticon-working-group', 'Some groups manage lots of little events, our working group focuses all our attention on creating the single, biggest, and best Mautic-focused event of the year. Want to help organize the annual Mauticon? Join us!', 0, '2018-06-28 12:42:35', '2018-06-30 13:15:32', null, 104427, '', '', 'working-group', 'fe-cast', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (48, 'Mauticamps Working Group', 'mauticamps-working-group', 'Can you imagine the fun of getting to work with people from all over the world? Our working group is focused on empowering local Mauticamps in cities across the globe. If you like giving people helpful tools to be successful running events join our group!', 0, '2018-06-28 12:42:52', '2018-06-30 13:15:20', null, 104425, '', '', 'working-group', 'fe-triangle', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (49, 'Accounting Working Group', 'accounting-working-group', 'Some people just have a thing for numbers. In our working group we are obsessed with them. We manage the books for the Mautic Association and make sure everything is accounted for properly. Interested?', 0, '2018-06-28 12:43:17', '2018-06-30 13:25:02', null, 104418, 'Some people just have a thing for numbers. In our working group we are obsessed with them. We manage the books for the Mautic Association and make sure everything is accounted for properly. Interested?', '<p>Some people just have a thing for numbers. In our working group we are obsessed with them. We manage the books for the Mautic Association and make sure everything is accounted for properly. Interested?</p>', 'working-group', 'fe-dollar-sign', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (50, 'Trademark Working Group', 'trademark-working-group', 'Do you love the Mautic brand and name as much as we do? If you''re interested in making sure Mautic looks right everywhere you see it then this is the working group for you.', 0, '2018-06-28 12:44:09', '2018-06-30 13:16:08', null, 104433, '', '', 'working-group', 'fe-heart', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (51, 'Strategy + Program Working Group', 'strategy-program-working-group', 'Every marketing department needs a strategy. Mautic is no different, and possibly even more so since we''re the world''s best marketing automation platform. Our marketing is super critical. If you like strategy, this team is for you.', 0, '2018-06-28 12:44:43', '2018-06-30 13:16:03', null, 104432, '', '', 'working-group', 'fe-map', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (52, 'Social Media Working Group', 'social-media-working-group', 'Interested in working in social media? Can''t get enough Facebook, Twitter, or LinkedIn? This is the working group for you. Help us share the Mautic story through social media channels!', 0, '2018-06-28 12:45:09', '2018-06-30 13:15:59', null, 104431, '', '', 'working-group', 'fe-twitter', '', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (53, 'Turkish (tr)', 'turkish-tr', '', 0, '2018-07-03 02:10:29', '2018-07-03 02:21:00', null, 68641, '', '', 'translation', 'flag flag-tr', '', 'https://www.transifex.com/mautic/mautic/language/tr/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (54, 'Spanish (es)', 'spanish-es', '', 0, '2018-07-03 02:12:52', '2018-07-03 02:20:52', null, 68641, '', '', 'translation', 'flag flag-es', '', 'https://www.transifex.com/mautic/mautic/language/es/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (55, 'Bulgarian (bg)', 'bulgarian-bg', '', 0, '2018-07-03 02:13:22', '2018-07-03 02:20:36', null, 68641, '', '', 'translation', 'flag flag-bg', '', 'https://www.transifex.com/mautic/mautic/language/bg_BG', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (56, 'French (fr)', 'french-fr', '', 0, '2018-07-03 02:19:33', '2018-07-03 02:20:03', null, 68641, '', '', 'translation', 'flag flag-fr', '', 'https://www.transifex.com/mautic/mautic/language/fr/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (57, 'Hebrew (il)', 'hebrew-il', '', 0, '2018-07-03 02:22:10', '2018-07-03 02:22:10', null, 68641, '', '', 'translation', 'flag flag-il', '', 'https://www.transifex.com/mautic/mautic/language/he_IL/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (58, 'Portuguese (br)', 'portuguese-br', '', 0, '2018-07-03 02:22:55', '2018-07-03 02:22:55', null, 68641, '', '', 'translation', 'flag flag-br', '', 'https://www.transifex.com/mautic/mautic/language/pt_BR', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (59, 'Italian (it)', 'italian-it', '', 0, '2018-07-03 02:23:45', '2018-07-03 02:23:45', null, 68641, '', '', 'translation', 'flag flag-it', '', 'https://www.transifex.com/mautic/mautic/language/it_IT', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (60, 'Chinese (zh)', 'chinese-zh', '', 0, '2018-07-03 02:24:27', '2018-07-03 02:24:27', null, 68641, '', '', 'translation', 'flag flag-cn', '', 'https://www.transifex.com/mautic/mautic/language/zh_CN', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (61, 'English UK (gb)', 'english-uk-gb', '', 0, '2018-07-03 02:25:07', '2018-07-03 02:25:07', null, 68641, '', '', 'translation', 'flag flag-gb', '', 'https://www.transifex.com/mautic/mautic/language/en_GB/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (62, 'Vietnamese (vn)', 'vietnamese-vn', '', 0, '2018-07-03 02:36:23', '2018-07-03 02:36:23', null, 68641, '', '', 'translation', 'flag flag-vn', '', 'https://www.transifex.com/mautic/mautic/language/vi_VN/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (63, 'German (de)', 'german-de', '', 0, '2018-07-03 02:36:51', '2018-07-03 02:36:51', null, 68641, '', '', 'translation', 'flag flag-de', '', 'https://www.transifex.com/mautic/mautic/language/de/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (64, 'Japanese (ja)', 'japanese-ja', '', 0, '2018-07-03 02:37:15', '2018-07-03 03:03:21', null, 68641, '', '', 'translation', 'flag flag-jp', '', 'https://www.transifex.com/mautic/mautic/language/ja/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (65, 'Chinese Simplified (zh)', 'chinese-simplified-zh', '', 0, '2018-07-03 02:37:43', '2018-07-03 02:38:09', null, 68641, '', '', 'translation', 'flag flag-cn', '', 'https://www.transifex.com/mautic/mautic/language/zh-Hans/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (66, 'Czech (cs)', 'czech-cs', '', 0, '2018-07-03 02:38:42', '2018-07-03 03:01:05', null, 68641, '', '', 'translation', 'flag flag-cz', '', 'https://www.transifex.com/mautic/mautic/language/cs/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (67, 'Dutch (nl)', 'dutch-nl', '', 0, '2018-07-03 02:39:06', '2018-07-03 02:39:06', null, 68641, '', '', 'translation', 'flag flag-nl', '', 'https://www.transifex.com/mautic/mautic/language/nl', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (68, 'Thai (th)', 'thai-th', '', 0, '2018-07-03 02:39:31', '2018-07-03 02:39:31', null, 68641, '', '', 'translation', 'flag flag-th', '', 'https://www.transifex.com/mautic/mautic/language/th/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (69, 'Polish (pl)', 'polish-pl', '', 0, '2018-07-03 02:39:55', '2018-07-03 02:39:55', null, 68641, '', '', 'translation', 'flag flag-pl', '', 'https://www.transifex.com/mautic/mautic/language/pl_PL', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (70, 'Portuguese (pt)', 'portuguese-pt', '', 0, '2018-07-03 02:40:31', '2018-07-03 02:40:31', null, 68641, '', '', 'translation', 'flag flag-pt', '', 'https://www.transifex.com/mautic/mautic/language/pt_PT', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (71, 'Catalan (ca)', 'catalan-ca', '', 0, '2018-07-03 02:40:53', '2018-07-03 03:00:51', null, 68641, '', '', 'translation', 'flag flag-es', '', 'https://www.transifex.com/mautic/mautic/language/ca_ES/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (72, 'Russian (ru)', 'russian-ru', '', 0, '2018-07-03 02:41:15', '2018-07-03 02:41:15', null, 68641, '', '', 'translation', 'flag flag-ru', '', 'https://www.transifex.com/mautic/mautic/language/ru', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (73, 'Filipino (fil)', 'filipino-fil', '', 0, '2018-07-03 02:41:37', '2018-07-03 03:02:34', null, 68641, '', '', 'translation', 'flag flag-ph', '', 'https://www.transifex.com/mautic/mautic/language/fil/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (74, 'Chinese Taiwan (zh)', 'chinese-taiwan-zh', '', 0, '2018-07-03 02:42:06', '2018-07-03 02:42:06', null, 68641, '', '', 'translation', 'flag flag-tw', '', 'https://www.transifex.com/mautic/mautic/language/zh_TW/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (75, 'Finnish (fi)', 'finnish-fi', '', 0, '2018-07-03 02:42:33', '2018-07-03 02:42:33', null, 68641, '', '', 'translation', 'flag flag-fi', '', 'https://www.transifex.com/mautic/mautic/language/fi/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (76, 'Hungarian (hu)', 'hungarian-hu', '', 0, '2018-07-03 02:43:04', '2018-07-03 02:43:04', null, 68641, '', '', 'translation', 'flag flag-hu', '', 'https://www.transifex.com/mautic/mautic/language/hu', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (77, 'Norwegian (nb)', 'norwegian-nb', '', 0, '2018-07-03 02:43:32', '2018-07-03 03:04:16', null, 68641, '', '', 'translation', 'flag flag-no', '', 'https://www.transifex.com/mautic/mautic/language/nb_NO/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (78, 'Korean (ko)', 'korean-ko', '', 0, '2018-07-03 02:44:03', '2018-07-03 03:03:54', null, 68641, '', '', 'translation', 'flag flag-kr', '', 'https://www.transifex.com/mautic/mautic/language/ko_KR/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (79, 'Swedish (sv)', 'swedish-sv', '', 0, '2018-07-03 02:44:25', '2018-07-03 02:44:25', null, 68641, '', '', 'translation', 'flag flag-sv', '', 'https://www.transifex.com/mautic/mautic/language/sv/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (80, 'Ukrainian (ua)', 'ukrainian-ua', '', 0, '2018-07-03 02:44:59', '2018-07-03 02:44:59', null, 68641, '', '', 'translation', 'flag flag-ua', '', 'https://www.transifex.com/mautic/mautic/language/uk_UA/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (81, 'Lithuanian (lt)', 'lithuanian-lt', '', 0, '2018-07-03 02:45:23', '2018-07-03 02:45:23', null, 68641, '', '', 'translation', 'flag flag-lt', '', 'https://www.transifex.com/mautic/mautic/language/lt_LT/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (82, 'Indonesian (id)', 'indonesian-id', '', 0, '2018-07-03 02:45:46', '2018-07-03 02:45:46', null, 68641, '', '', 'translation', 'flag flag-id', '', 'https://www.transifex.com/mautic/mautic/language/id_ID/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (83, 'Romanian (ro)', 'romanian-ro', '', 0, '2018-07-03 02:46:06', '2018-07-03 02:46:06', null, 68641, '', '', 'translation', 'flag flag-ro', '', 'https://www.transifex.com/mautic/mautic/language/ro_RO/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (84, 'Persian (fa)', 'persian-fa', '', 0, '2018-07-03 02:46:36', '2018-07-03 02:46:36', null, 68641, '', '', 'translation', 'flag flag-ir', '', 'https://www.transifex.com/mautic/mautic/language/fa_IR/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (85, 'Danish (da)', 'danish-da', '', 0, '2018-07-03 02:46:58', '2018-07-03 03:01:51', null, 68641, '', '', 'translation', 'flag flag-dk', '', 'https://www.transifex.com/mautic/mautic/language/da/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (86, 'Greek (el)', 'greek-el', '', 0, '2018-07-03 02:47:16', '2018-07-03 03:02:57', null, 68641, '', '', 'translation', 'flag flag-gr', '', 'https://www.transifex.com/mautic/mautic/language/el/', null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (105, 'MautiCamp Tokyo', 'mautic-meetup-tokyo', 'Mautic は、モダンなPHPアーキテクチャで構築されたオープンソースのマーケティングオートメーションソフトウェアです。この素晴らしいマーケティングプラットフォームに興味のある日本のすべての方と、Mautic の使い方やカスタマイズ方法のベストプラクティスなどの知識を共有するための Meetup です。', 0, '2017-12-08 21:46:00', '2017-12-08 21:46:00', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (106, 'MautiCamp Eindhoven', 'mautic-meetup-eindhoven', 'Mautic is een open source marketing automation software gebouwd op de nieuwste PHP-architectuur.

Ontmoet om kennis te delen met iedereen in Eindhoven, Nederland die geïnteresseerd is in dit prachtige marketingplatform, inclusief best practices over hoe', 0, '2017-12-08 23:31:03', '2017-12-08 23:31:03', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (107, 'MautiCamp Sapporo', 'mautic-meetup-sapporo', 'Mauticは、最新のPHPアーキテクチャー上に構築されたオープンソースのマーケティングオートメーションソフトウェアです。

Mauticの使い方とカスタマイズ方法に関するベストプラクティスなど、この素晴らしいマーケティングプラットフォームに興味を持っている札幌の皆さんの知識を共有しましょう。', 0, '2017-12-09 03:09:36', '2017-12-09 03:09:36', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (108, 'MautiCamp Ipswich', 'mautic-meetup-ipswich', 'Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge of everyone in Ipswich who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how', 0, '2017-12-09 03:10:57', '2017-12-09 03:10:57', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (109, 'MautiCamp Raleigh', 'mautic-meetup-raleigh', 'Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge of everyone in Raleigh who is interested in this wonderful marketing platform, including best practices on how to use Mautic and how', 0, '2017-12-09 03:11:59', '2017-12-09 03:11:59', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (110, 'MautiCamp Curitiba', 'mautic-meetup-curitiba', 'Mautic é um software de automação de marketing de código aberto, construído sobre a arquitetura PHP mais recente.

Encontre-se para compartilhar conhecimento com todos em Curitiba, Brasil, que está interessado nesta maravilhosa plataforma de marketing, ', 0, '2017-12-10 02:57:05', '2017-12-10 02:57:05', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (111, 'MautiCamp Johannesburg', 'johannesburg', 'Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in Johannesburg who is interested in this wonderful marketing platform, including best practices on how to use Mautic ', 0, '2017-12-10 03:01:39', '2017-12-10 03:01:39', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (112, 'MautiCamp Málaga', 'mautic-meetup-malaga-2046896914', 'Mautic es un software de automatización de marketing de código abierto basado en la última arquitectura de PHP.

Reúnete para compartir conocimientos con todos los que están interesados en esta maravillosa plataforma de marketing, incluidas las mejores ', 0, '2017-12-10 03:04:26', '2017-12-10 03:04:26', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (113, 'MautiCamp San Francisco', 'mautic-meetup-san-francisco', 'Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in San Francisco who is interested in this wonderful marketing platform, including best practices on how to use Mautic', 0, '2017-12-10 03:05:16', '2017-12-10 03:05:16', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (114, 'MautiCamp Atlanta', 'atlanta', 'Anyone located in the Atlanta, GA metro area. ITP, OTP, doesn\\''t matter. Come join us!', 0, '2017-12-22 23:49:41', '2017-12-22 23:49:41', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (115, 'MautiCamp Saudi Arabia', 'mauticamp-saudi-arabia', 'Mautic is an open source marketing automation software built on the latest PHP architecture.
Meet up to share knowledge with everyone in Saudi Arabia who is interested in this wonderful marketing platform.
Use this platform and boost your business, your', 0, '2017-12-28 14:07:19', '2017-12-28 14:07:19', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (116, 'MautiCamp Pakistan', 'mauticamp-pakistan', 'Mautic is an open source marketing automation software built on the latest PHP architecture.
Meet up to share knowledge with everyone in Pakistan who is interested in this wonderful marketing platform.
Use this platform and boost your business, your bra', 0, '2017-12-28 14:17:06', '2017-12-28 14:17:06', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (117, 'Mauticamp East Midlands', 'mauticamp-east-midlands', 'Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in the East Midlands (UK) who is interested in this wonderful marketing platform, including best practices on how to u', 0, '2018-01-03 14:22:25', '2018-01-03 14:22:25', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (118, 'MautiCamp Vietnam', 'mauticamp-vietnam', 'Mautic là một phần mềm tự động hóa tiếp thị mã nguồn mở được xây dựng trên kiến ​​trúc PHP mới nhất.
Đây là nơi dành cho người Việt Nam - những người quan tâm đến nền tảng tiếp thị tuyệt vời chia sẻ kiến thức.', 0, '2018-01-20 07:36:41', '2018-01-20 07:36:41', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (119, 'MautiCamp Latinoamérica', 'mauticamp-latinoamerica', 'Bienvenido(a) a la Comunidad de MautiCamp Latinoamérica para: Perú, Colombia, Ecuador, Chile, Argentina, México, entre otros.

Mautic es el primer software open source de automatización del marketing más completo. Posee características avanzadas para ge', 0, '2018-02-11 02:51:36', '2018-02-11 02:51:36', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (120, 'Mautic ישראל', 'mautic-%d7%99%d7%a9%d7%a8%d7%90%d7%9c', 'מאוטיק היא תוכנת מארקטינג אוטומיישן מבוססת קוד פתוח שנבנתה על תשתית פי.אייץ\\''.פי. כאן ניתן להפגש ולחלוק מידע עם כל מי שמתעניין במערכת זו, כולל מידע על שיטות עבודה מומלצות וכיצד ניתן לבצע במערכת התאמות אישיות', 0, '2018-03-04 13:48:37', '2018-03-04 13:48:37', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (121, 'Rio de Janeiro', 'rio-de-janeiro', 'Encontro de usuários do Mautic no Rio de Janeiro', 0, '2018-04-17 20:35:19', '2018-04-17 20:35:19', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);
INSERT INTO mtorg_db.trka_groups_groups (id, name, slug, description, parent, created_at, updated_at, deleted_at, forum_channel_id, homepage_content, homepage_content_html, group_type, group_icon, group_color, transifex_url, notices, sidebar_slots) VALUES (122, 'Mautic Vancouver', 'mautic-vancouver-795395371', 'Join this group if you are in Vancouver Canada.  Let\\''s share our Mautic knowledge to create butt-kicking marketing campaigns.  :)', 0, '2018-05-05 03:50:30', '2018-05-05 03:50:30', null, null, null, null, 'mauticamp', 'fe-users', 'gray', null, null, null);