CREATE TABLE mtorg_db.rainlab_forum_channels
(
    id int(10) unsigned PRIMARY KEY NOT NULL AUTO_INCREMENT,
    parent_id int(10) unsigned,
    title varchar(191),
    slug varchar(191) NOT NULL,
    description varchar(191),
    nest_left int(11),
    nest_right int(11),
    nest_depth int(11),
    count_topics int(11) DEFAULT 0 NOT NULL,
    count_posts int(11) DEFAULT 0 NOT NULL,
    created_at timestamp,
    updated_at timestamp,
    is_hidden tinyint(1) DEFAULT 0 NOT NULL,
    is_moderated tinyint(1) DEFAULT 0 NOT NULL,
    embed_code varchar(191)
);
CREATE UNIQUE INDEX rainlab_forum_channels_slug_unique ON mtorg_db.rainlab_forum_channels (slug);
CREATE INDEX rainlab_forum_channels_parent_id_index ON mtorg_db.rainlab_forum_channels (parent_id);
CREATE INDEX rainlab_forum_channels_embed_code_index ON mtorg_db.rainlab_forum_channels (embed_code);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (68635, 104416, 'General Discussion', 'general-discussion', 'This channel is for all things Mautic. Post here to discuss marketing automation, marketing ideas and general queries. 
', 1, 14, 0, 1487, 5265, '2017-12-14 20:56:54', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (68636, null, 'MautiCamps', 'meetups', 'This channel is for organizers, planners, and event coordinators looking to form a MautiCamp™', 1, 14, 0, 34, 129, '2017-12-14 20:56:54', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (68637, 104416, 'Support', 'support', 'This channel focuses on people helping people. Mautic is here for you.', 1, 14, 0, 4301, 15920, '2017-12-14 20:56:54', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (68638, 104416, 'Development', 'development', 'This channel is geared toward making Mautic the best it can be. 
', 1, 14, 0, 412, 1341, '2017-12-14 20:56:54', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (68639, 104416, 'Docs', 'docs', 'This channel is for those interested in improving Mautic documentation.', 1, 14, 0, 23, 59, '2017-12-14 20:56:54', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (68640, 104416, 'Design', 'design', 'Discuss improvements and changes to the Mautic UI/UX and themes.
', 1, 14, 0, 23, 65, '2017-12-14 20:56:54', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (68641, null, 'Translation', 'translation', 'Translate Mautic to your native language and contribute to the spread of this powerful tool throughout the world.', 1, 14, 0, 23, 95, '2017-12-14 20:56:54', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (68642, 104416, 'Blog', 'blog', 'Ideas, Case Studies, Articles, and more. 
Share, learn, connect', 1, 14, 0, 7, 16, '2017-12-14 20:56:54', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (68643, 104416, 'Ideas', 'ideas', 'Put your best ideas and feature requests here! Vote on the ones you like the best', 1, 14, 0, 170, 317, '2017-12-14 20:56:54', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (68645, null, 'Locales', 'locales', 'This channel is for the creation of Mautic.org locales to provide organizational content in individual languages', 1, 14, 0, 2, 5, '2017-12-14 20:56:54', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (68646, 104416, 'Announcements', 'announcements', 'This channel dedicated to Mautic News and Announcements', 1, 14, 0, 28, 306, '2017-12-14 20:56:54', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (68647, 104416, '3rd Party Addons', '3rd-party-addons', 'A place for 3rd party developers to announce their addons and for the community to discuss and/or seek support for them.', 1, 14, 0, 98, 683, '2017-12-14 20:56:54', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (102197, 68636, 'MautiCamp Singapore', 'mauticcamp-singapore', 'Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in Singapore who is interested in this wonderful marke', 1, 14, 0, 0, 0, '2017-12-23 02:17:39', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (102198, 68636, 'MautiCamp Malaysia', 'mauticamp-malaysia', 'Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in Malaysia who is interested in this wonderful market', 1, 14, 0, 0, 0, '2017-12-23 02:33:37', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (102220, 68636, 'MautiCamp Hungary', 'mauticamp-hungary', 'Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in Hungary who is interested in this wonderful marketi', 1, 14, 0, 0, 0, '2017-12-26 15:14:04', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (102229, 68636, 'MautiCamp India', 'mauticamps-india', 'Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in INDIA who is interested in this wonderful marketing', 1, 14, 0, 0, 0, '2017-12-26 16:45:07', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (102240, 68636, 'MautiCamp Saudi Arabia', 'mauticamp-saudi-arabia', 'Mautic is an open source marketing automation software built on the latest PHP architecture.
Meet up to share knowledge with everyone in Saudi Arabia who is interested in this wonderful mark', 1, 14, 0, 0, 0, '2017-12-28 09:07:29', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (102241, 68636, 'MautiCamp Pakistan', 'mauticamp-pakistan', 'Mautic is an open source marketing automation software built on the latest PHP architecture.
Meet up to share knowledge with everyone in Pakistan who is interested in this wonderful marketin', 1, 14, 0, 0, 0, '2017-12-28 09:17:12', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (102243, 68636, 'MautiCamp Italia', 'mauticamp-italia', 'Mautic is an open source marketing automation software built on the latest PHP architecture.
Meet up to share knowledge with everyone in Italy who is interested in this wonderful marketing p', 1, 14, 0, 1, 5, '2017-12-28 18:55:32', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (102291, 68636, 'Mauticamp East Midlands', 'mauticamp-east-midlands', 'Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in the East Midlands (UK) who is interested in this wo', 1, 14, 0, 0, 0, '2018-01-03 09:58:34', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (102406, 68636, 'MautiCamp Sweden', 'mauticamp-sweden', 'For all swedish mauticians', 1, 14, 0, 0, 0, '2018-01-08 18:48:31', '2018-06-10 11:13:18', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (102636, 68636, 'MautiCamp Vietnam', 'mauticamp-vietnam', 'Mautic là một phần mềm tự động hóa tiếp thị mã nguồn mở được xây dựng trên kiến ​​trúc PHP mới nhất.
Đây là nơi dành cho người Việt Nam - những người quan tâm đến nền tảng tiếp thị tuyệt vời', 1, 14, 0, 0, 0, '2018-01-20 02:37:05', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (102673, 68636, 'Mauticamp South Africa', 'mauticamp-south-africa', 'Corporate Strength Marketing for All.
Now Small businesses can also market like the big guys...With Mautic levelling the playing fields.', 1, 14, 0, 0, 0, '2018-01-21 05:47:18', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (103048, 68636, 'MautiCamp Latinoamérica', 'mauticamp-latinoamerica', 'Bienvenido(a) a la Comunidad de MautiCamp Latinoamérica para: Perú, Colombia, Ecuador, Chile, Argentina, México, entre otros.

Mautic es el primer software open source de automatización del', 1, 14, 0, 0, 0, '2018-02-10 21:52:04', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (103447, 68636, 'Mautic ישראל', 'mautic-%d7%99%d7%a9%d7%a8%d7%90%d7%9c', 'מאוטיק היא תוכנת Marketing Automation מבוססת קוד פתוח שנבנתה על תשתית PHP. כאן ניתן להפגש ולחלוק מידע עם כל מי שמתעניין במערכת זו, כולל מידע על שיטות עבודה מומלצות וכיצד ניתן לבצע במערכת התאמ', 1, 14, 0, 0, 0, '2018-03-04 08:48:45', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (103738, 68636, 'Mautic Hong Kong', 'mautic-hong-kong', 'Mautic is an open source marketing automation software built on the latest PHP architecture.

Meet up to share knowledge with everyone in Hong Kong who is interested in this wonderful marke', 1, 14, 0, 0, 0, '2018-03-16 01:24:30', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (104231, 68636, 'Rio de Janeiro', 'rio-de-janeiro', 'Encontro de usuários do Mautic no Rio de Janeiro', 1, 14, 0, 0, 0, '2018-04-17 16:35:29', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (104412, 68636, 'Mautic Vancouver', 'mautic-vancouver', 'Vancouverites unite!    Join this group if you are in the Vancouver lower mainland.    Let&#039;s maximize our mautic knowledge by sharing information to produce butt-kicking marketing campai', 1, 14, 0, 0, 0, '2018-05-04 23:44:28', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (104413, 68636, 'Mautic Vancouver', 'mautic-vancouver-2', 'Join this group if you are in Vancouver Canada.  Let&#039;s share our Mautic knowledge to create butt-kicking marketing campaigns.  :)', 1, 14, 30, 0, 0, '2018-05-04 23:50:34', '2018-06-10 11:11:11', 0, 0, null);
INSERT INTO mtorg_db.rainlab_forum_channels (id, parent_id, title, slug, description, nest_left, nest_right, nest_depth, count_topics, count_posts, created_at, updated_at, is_hidden, is_moderated, embed_code) VALUES (104416, null, 'Discussion', 'discussion', '', 1, 14, 0, 0, 0, '2018-06-10 10:54:15', '2018-06-10 11:11:11', 0, 0, null);